<?php

namespace KernelBundle\Repository;

/**
 * DivisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisionRepository extends DoleticRepository
{
}
