<?php

namespace KernelBundle\Repository;

/**
 * DocumentTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTemplateRepository extends DoleticRepository
{
}
