<?php

namespace KernelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('q')
            ->select('e')
            ->from('KernelBundle:Gender', 'e', 'e.id')
            ->getQuery()->getResult();
    }
}
