<?php

namespace KernelBundle\Repository;

/**
 * GenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderRepository extends DoleticRepository
{
}
