<?php

namespace KernelBundle\Repository;

/**
 * MailingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingListRepository extends \Doctrine\ORM\EntityRepository
{
}
