<?php

namespace KernelBundle\Repository;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends DoleticRepository
{
}
