<?php

namespace KernelBundle\Repository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends DoleticRepository
{
}
