<?php

namespace KernelBundle\Repository;

/**
 * UserPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPositionRepository extends DoleticRepository
{
    public function getAllUserPositions()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select up from KernelBundle:UserPosition as up'
        );
        return $qb->getResult();
    }
}
