<?php

namespace KernelBundle\Repository;

/**
 * UserPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPositionRepository extends DoleticRepository
{
}
