<?php

namespace RHBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultantMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantMembershipRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('q')
            ->select('e')
            ->from('RHBundle:ConsultantMembership', 'e', 'e.id')
            ->getQuery()->getResult();
    }
}
