<?php

namespace RHBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ConsultantMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantMembershipRepository extends DoleticRepository
{
}
