<?php

namespace RHBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends DoleticRepository
{
}
