<?php

namespace RHBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends DoleticRepository
{
}
