<?php

namespace RHBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberRepository extends EntityRepository
{
}
