<?php

namespace RHBundle\Repository;

use Doctrine\ORM\EntityRepository;
use KernelBundle\Entity\User;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function findUserTeams(User $member)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->join('t.members', 'm')->where($qb->expr()->eq('m.id', $member->getId()));
        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('q')
            ->select('e')
            ->from('RHBundle:Team', 'e', 'e.id')
            ->getQuery()->getResult();
    }
}
