<?php

namespace RHBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * TeamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberRepository extends DoleticRepository
{
}
