<?php

namespace SupportBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends DoleticRepository
{
}
