<?php

namespace SupportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('q')
            ->select('e')
            ->from('SupportBundle:TicketType', 'e', 'e.id')
            ->getQuery()->getResult();
    }
}
