<?php

namespace DTBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

class DocumentRepository extends EntityRepository
{

    public function getCurrentDocuments(){
        return $this->findByDeprecated(false);
    }


}
