services:
    ## ENTITY LISTENERS
    user_listener:
        class: KernelBundle\Listener\UserListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    user_position_listener:
        class: KernelBundle\Listener\UserPositionListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    position_listener:
        class: KernelBundle\Listener\PositionListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    ## VALIDATORS
    kernel.correct_password_validator:
        class: KernelBundle\Validator\Constraints\CorrectPasswordValidator
        arguments: ['@security.encoder_factory', '@security.token_storage']
        tags:
            - { name: validator.constraint_validator }

    ## OVH API SERVICES
    ovh_mail_manager:
        class: KernelBundle\Service\OVHMailManager
        arguments: ['%ovh_endpoint%', '%ovh_application_key%', '%ovh_application_secret%', '%ovh_consumer_key%', '%je_domain%', '%mailing_language%']

    ## UPLOAD SERVICES
    document_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%documents_dir%']

    avatar_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%avatars_dir%']

    template_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%templates_dir%']

    ## TEMPLATING SERVICES
    document_publisher:
        class: KernelBundle\Service\DocumentPublisher
        arguments: ['%output_dir%']

    ## OTHER SERVICES
    mailing_list_service:
        class: KernelBundle\Service\MailingListService
        arguments: ['@doctrine.orm.entity_manager']
