services:
    ## UPLOAD SERVICES
    document_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%documents_dir%']

    avatar_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%avatars_dir%']

    template_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%templates_dir%']

    ## TEMPLATING SERVICES
    document_publisher:
        class: KernelBundle\Service\DocumentPublisher
        arguments: ['%output_dir%']