services:
    ## ENTITY LISTENERS
    user_position_listener:
        class: KernelBundle\Listener\UserPositionListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    position_listener:
        class: KernelBundle\Listener\PositionListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    ## UPLOAD SERVICES
    document_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%documents_dir%']

    avatar_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%avatars_dir%']

    template_uploader:
        class: KernelBundle\Service\FileUploader
        arguments: ['%templates_dir%']

    ## TEMPLATING SERVICES
    document_publisher:
        class: KernelBundle\Service\DocumentPublisher
        arguments: ['%output_dir%']