# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
                    id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:      ^/(_(profiler|wdt)|css|images|js)/
            security:     false

        oauth_token:
            pattern:      ^/oauth/v2/token
            security:     false

        api_doc:
            pattern:      ^/api/doc
            security:     false

        api:
            pattern:      ^/api
            fos_oauth:    true
            stateless:    true

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api/kernel, roles: [ ROLE_KERNEL_GUEST ] }
        - { path: ^/api/rh, roles: [ ROLE_RH_GUEST ] }
        - { path: ^/api/grc, roles: [ ROLE_GRC_GUEST ] }
        - { path: ^/api/ua, roles: [ ROLE_UA_GUEST ] }
        - { path: ^/api/support, roles: [ ROLE_SUPPORT_GUEST ] }

    role_hierarchy:
        # Global roles - to be updated when a new module (bundle) is added
        ROLE_SUPERADMIN: [ROLE_KERNEL_SUPERADMIN, ROLE_RH_SUPERADMIN, ROLE_GRC_SUPERADMIN, ROLE_UA_SUPERADMIN, ROLE_SUPPORT_SUPERADMIN]
        ROLE_ADMIN: [ROLE_KERNEL_ADMIN, ROLE_RH_ADMIN, ROLE_GRC_ADMIN, ROLE_UA_ADMIN, ROLE_SUPPORT_ADMIN]
        ROLE_USER: [ROLE_KERNEL_USER, ROLE_RH_USER, ROLE_GRC_USER, ROLE_UA_USER, ROLE_SUPPORT_USER]
        ROLE_GUEST: [ROLE_KERNEL_GUEST, ROLE_RH_GUEST, ROLE_GRC_GUEST, ROLE_UA_GUEST, ROLE_SUPPORT_GUEST]

        # Module (bundle) roles - add roles when a module is added
        # Kernel Module
        ROLE_KERNEL_SUPERADMIN: [ROLE_KERNEL_ADMIN]
        ROLE_KERNEL_ADMIN: [ROLE_KERNEL_USER]
        ROLE_KERNEL_USER: [ROLE_KERNEL_GUEST]
        ROLE_KERNEL_GUEST: ~

        # RH Module
        ROLE_RH_SUPERADMIN: [ROLE_RH_ADMIN]
        ROLE_RH_ADMIN: [ROLE_RH_USER]
        ROLE_RH_USER: [ROLE_RH_GUEST]
        ROLE_RH_GUEST: ~

        # GRC Module
        ROLE_GRC_SUPERADMIN: [ROLE_GRC_ADMIN]
        ROLE_GRC_ADMIN: [ROLE_GRC_USER]
        ROLE_GRC_USER: [ROLE_GRC_GUEST]
        ROLE_GRC_GUEST: ~

        # UA Module
        ROLE_UA_SUPERADMIN: [ROLE_UA_ADMIN]
        ROLE_UA_ADMIN: [ROLE_UA_USER]
        ROLE_UA_USER: [ROLE_UA_GUEST]
        ROLE_UA_GUEST: ~

        # Support Module
        ROLE_SUPPORT_SUPERADMIN: [ROLE_SUPPORT_ADMIN]
        ROLE_SUPPORT_ADMIN: [ROLE_SUPPORT_USER]
        ROLE_SUPPORT_USER: [ROLE_SUPPORT_GUEST]
        ROLE_SUPPORT_GUEST: ~