# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user_data_listener:
        class: RHBundle\Listener\UserDataListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    contact_listener:
        class: GRCBundle\Listener\ContactListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    ticket_listener:
        class: SupportBundle\Listener\TicketListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_listener:
        class: UABundle\Listener\ProjectListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    task_listener:
        class: UABundle\Listener\TaskListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    consultant_listener:
        class: UABundle\Listener\ConsultantListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }