<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;
use UABundle\Entity\AmendmentType;

/**
 * AmendmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentRepository extends EntityRepository
{
    public function findByType(AmendmentType $type)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->join('a.types', 't')->where($qb->expr()->eq('t.id', $type->getId()));
        return $qb->getQuery()->getResult();
    }
}
