<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmendmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmendmentTypeRepository extends EntityRepository
{
}
