<?php

namespace UABundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use GRCBundle\Entity\Contact;
use KernelBundle\Entity\User;
use KernelBundle\Repository\DoleticRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends DoleticRepository
{

}
