<?php

namespace UABundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantRepository extends DoleticRepository
{
    public function getAllConsultants()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select c from UABundle:Consultant as c ORDER BY c.number'
        );
        return $qb->getResult();
    }
}
