<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultantDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantDocumentRepository extends EntityRepository
{
}
