<?php

namespace UABundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ConsultantDocumentTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantDocumentTemplateRepository extends DoleticRepository
{
}
