<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;
use UABundle\Entity\Project;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends EntityRepository
{
    public function findByProject(Project $project)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->join('d.task', 't')->where($qb->expr()->eq('t.project', $project->getId()));
        return $qb->getQuery()->getResult();
    }
}
