<?php

namespace UABundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ProjectContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectContactRepository extends DoleticRepository
{
}
