<?php

namespace UABundle\Repository;

use GRCBundle\Entity\Contact;
use KernelBundle\Entity\User;
use KernelBundle\Repository\DoleticRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends DoleticRepository
{
    public function findByManager(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.managers', 'm')->where($qb->expr()->eq('m.id', $user->getId()))
            ->orderBy('p.number', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function findByContact(Contact $contact)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.contacts', 'c')->where($qb->expr()->eq('c.id', $contact->getId()))
            ->orderBy('p.number', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function findByConsultant(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.consultants', 'c')->where($qb->expr()->eq('c.user', $user->getId()))
            ->orderBy('p.number', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
