<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFieldRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('q')
            ->select('e')
            ->from('UABundle:ProjectField', 'e', 'e.id')
            ->getQuery()->getResult();
    }
}
