<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectManagerRepository extends EntityRepository
{
}
