<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;
use GRCBundle\Entity\Contact;
use KernelBundle\Entity\User;
use RHBundle\Entity\UserData;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findByManager(UserData $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.managers', 'c')->where($qb->expr()->eq('c.id', $user->getId()))
            ->orderBy(['p.number' => 'DESC']);
        return $qb->getQuery()->getResult();
    }

    public function findByContact(Contact $contact)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.contacts', 'c')->where($qb->expr()->eq('c.id', $contact->getId()))
            ->orderBy(['p.number' => 'DESC']);
        return $qb->getQuery()->getResult();
    }

    public function findByConsultant(UserData $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.consultants', 'c')->where($qb->expr()->eq('c.userData', $user->getId()))
            ->orderBy(['p.number' => 'DESC']);
        return $qb->getQuery()->getResult();
    }
}
