<?php

namespace UABundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStatusRepository extends EntityRepository
{
}
