<?php

namespace UABundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ProjectOriginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectOriginRepository extends DoleticRepository
{
}
