<?php

namespace UABundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends DoleticRepository
{
    public function getAllTasks()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select t from UABundle:Task as t ORDER BY t.number'
        )->setMaxResults(100);
        return $qb->getResult();
    }
}
