services:
    ticket_listener:
        class: SupportBundle\Listener\TicketListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }