<?php

namespace GRCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactTypeRepository extends EntityRepository
{
}
