<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ContactActionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactActionTypeRepository extends DoleticRepository
{
}
