<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ContactTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactTypeRepository extends DoleticRepository
{
}
