<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends DoleticRepository
{
    public function getContactsByType($type)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select c from GRCBundle:Contact as c, GRCBundle:ContactType as ct where ct.id = ?1 and c.type = ct'
        )->setParameter(1, $type);
        return $qb->getResult();
    }

    public function getAllContacts()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select c from GRCBundle:Contact as c'
        );
        return $qb->getResult();
    }
}
