<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * ContactActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactActionRepository extends DoleticRepository
{
}
