<?php

namespace GRCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactActionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactActionTypeRepository extends EntityRepository
{
}
