<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends DoleticRepository
{
    public function getContactsByType($type, $page, $max)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select c from GRCBundle:Contact as c, GRCBundle:ContactType as ct where ct.id = ?1 and c.type = ct'
        )->setParameter(1, $type);

        $adaptater = new DoctrineORMAdapter($qb,true,false);
        $pagerfanta = new Pagerfanta($adaptater);


        $max = min($pagerfanta->getNbResults(), $max);
        $page = min($pagerfanta->getNbPages(), $page);

        $entities = $pagerfanta
            ->setMaxPerPage($max)
            ->setCurrentPage($page)
            ->getCurrentPageResults();

        return iterator_to_array($entities);
    }

    public function getAllContacts($page, $max)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQuery(

            'select c from GRCBundle:Contact as c'
        );

        $adaptater = new DoctrineORMAdapter($qb,true,false);
        $pagerfanta = new Pagerfanta($adaptater);


        $max = min($pagerfanta->getNbResults(), $max);
        $page = min($pagerfanta->getNbPages(), $page);

        $entities = $pagerfanta
            ->setMaxPerPage($max)
            ->setCurrentPage($page)
            ->getCurrentPageResults();

        return iterator_to_array($entities);
    }
}
