<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * FirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmRepository extends DoleticRepository
{
    public function getFirmsForTab($page, $max)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select('f.id')
            ->addSelect('f.name')
            ->addSelect('f.siret')
            ->addSelect('t.label as type')
            ->addSelect('f.address')
            ->addSelect('f.postalCode')
            ->addSelect('f.city')
            ->addSelect('c.label as country')
            ->from('GRCBundle:Firm', 'f')
            ->join('f.type', 't')
            ->join('f.country', 'c');

        $adaptater = new DoctrineORMAdapter($qb,true,false);
        $pagerfanta = new Pagerfanta($adaptater);


        $max = min($pagerfanta->getNbResults(), $max);
        $page = min($pagerfanta->getNbPages(), $page);

        $entities = $pagerfanta
            ->setMaxPerPage($max)
            ->setCurrentPage($page)
            ->getCurrentPageResults();

        return iterator_to_array($entities);
    }
}
