<?php

namespace GRCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FirmTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmTypeRepository extends EntityRepository
{
}
