<?php

namespace GRCBundle\Repository;

use KernelBundle\Repository\DoleticRepository;

/**
 * FirmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmRepository extends DoleticRepository
{
    public function getFirmsForTab()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select('f.id')
            ->addSelect('f.name')
            ->addSelect('f.siret')
            ->addSelect('t.label as type')
            ->addSelect('f.address')
            ->addSelect('f.postalCode')
            ->addSelect('f.city')
            ->addSelect('c.label as country')
            ->from('GRCBundle:Firm', 'f')
            ->join('f.type', 't')
            ->join('f.country', 'c');

        return $qb->getQuery()->getResult();
    }
}
