services:
    project_listener:
        class: UABundle\Listener\ProjectListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    task_listener:
        class: UABundle\Listener\TaskListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    consultant_listener:
        class: UABundle\Listener\ConsultantListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }