services:
    project_listener:
        class: UABundle\Listener\ProjectListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_listener:
        class: UABundle\Listener\TaskListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_listener:
        class: UABundle\Listener\DeliveryListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_listener:
        class: UABundle\Listener\ConsultantListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }