services:
    ## ENTITY LISTENERS
    project_listener:
        class: UABundle\Listener\ProjectListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    task_listener:
        class: UABundle\Listener\TaskListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    consultant_listener:
        class: UABundle\Listener\ConsultantListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_manager_listener:
        class: UABundle\Listener\ProjectManagerListener
        arguments: []
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }

    project_contact_listener:
        class: UABundle\Listener\ProjectContactListener
        arguments: []
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }


    ## UPLOAD LISTENERS
    document_upload_listener:
        class: UABundle\Listener\DocumentUploadListener
        arguments: ['@document_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }

    ## UA SERVICES
    ua.project.rights_service:
        class: UABundle\Service\ProjectRightsService
        arguments: ['@security.authorization_checker']

    ua.document.service:
        class: UABundle\Service\DocumentService
        arguments: ['@doctrine.orm.entity_manager', '%tva_percent%', '%consultant_tax%']
