services:
    user_data_listener:
        class: RHBundle\Listener\UserDataListener
        tags:
            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.orm.entity_listener, entity_manager: custom }